#ifndef _MES_HARDWARE_MAP_H_
#define	_MES_HARDWARE_MAP_H_


////////////////////////////////////////////////////////////
//			HARDWARE INTERFACE DEFINITION
////////////////////////////////////////////////////////////

// REFERENCE : SERIAL COMM. PORT CONFIGRURATION
// SERIAL_5N1, SERIAL_6N1, SERIAL_7N1, SERIAL_8N1 (the default), SERIAL_5N2, SERIAL_6N2, SERIAL_7N2, SERIAL_8N2,
// SERIAL_5E1, SERIAL_6E1, SERIAL_7E1, SERIAL_8E1, SERIAL_5E2, SERIAL_6E2, SERIAL_7E2, SERIAL_8E2, 
// SERIAL_5O1, SERIAL_6O1, SERIAL_7O1, SERIAL_8O1, SERIAL_5O2, SERIAL_6O2, SERIAL_7O2, SERIAL_8O2

// SERIAL COMM. BAUDRATE FOR CONSOLE/USB(SERIAL)
#define CONSOLE_BAUD_RATE							(115200)			// 115200 [Baud] for Console/USB (Serial)
#define CONSOLE_COMM_CONFIG							(SERIAL_8N1)		// 8 sets data, Non parity bits, 1 stop bits
// SERIAL COMM. BAUDRATE FOR RS485(MODBUS RTU) BUS
#define RS485_BAUD_RATE								(19200)				// Max. Baud Rate of TM4 : 19200 [bps]
#define RS485_COMM_CONFIG1							(SERIAL_8N1)		// 8 sets data, Non parity bits, 1 stop bits
#define RS485_COMM_CONFIG2							(SERIAL_8N2)		// 8 sets data, Non parity bits, 2 stop bits
// SERIAL COMM. BAUDRATE FOR RS232(SERIAL) BUS
#define RS232_BAUD_RATE								(9600)				// Max. Baud Rate of Motor Controller : 9600 [bps]
#define RS232_COMM_CONFIG1							(SERIAL_8N1)		// 8 sets data, Non parity bits, 1 stop bits
#define RS232_COMM_CONFIG2							(SERIAL_8N2)		// 8 sets data, Non parity bits, 2 stop bits

// IIC BUS : Pin #21, #20
#define EXTERNAL_DEVICE_IIC_CONNECTED				(true)

// EXTERNAL INTERRUPT NUMBER OF ARDUINO MEGA
#define PIN_INTERRUPT_NUM_0							0					// External Interrupt pin : #2 (1)
#define PIN_INTERRUPT_NUM_1							1					// External Interrupt pin : #3 (2)
#if (!EXTERNAL_DEVICE_IIC_CONNECTED)
#define PIN_INTERRUPT_NUM_2							2 					// External Interrupt Pin : #21
#define PIN_INTERRUPT_NUM_3							3 					// External Interrupt Pin : #20
#endif
#define PIN_INTERRUPT_NUM_4							4 					// External Interrupt Pin : #19 (4)
#define PIN_INTERRUPT_NUM_5							5 					// External Interrupt Pin : #18 (3)


// ANALOG REFERENCE
#define ANALOG_READ_REF_TYPE						DEFAULT				// DEFAULT : INTERNAL, EXTERNAL (Must be Connected to External VCC)


////////////////////////////////////////////////////////////
// PIN ASSIGNMENTS (ARDUINO MEGA / CONTROLLINO MAXI)

#define _console									Serial 				// Serial #0 (RX0: #0,  TX0: #1 FOR ARDUNINO MEGA (USB OR PIN HEADER FOR CONTROLLINO MAXI))
#define _serial232									Serial2 			// Serial #2 (RX2: #17, TX2: #16 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI))
#define _serial485 									Serial3 			// Serial #3 (RX3: #15, TX3: #14 FOR ARDUINO MEGA (RS485 RX/TX FOR CONTROLLINO MAXI))
																		// TM4 : RS485(A)=(+), RS485(B)=(-) FOR CONTROLLINO MAXI(RS485 LINE DRIVER : SN65HVD08))

// BREW BUTTON SWITCH
#define BREW_BUTTON_SWITCH							2					// DIN(EINT) #2 FOR ARDUINO MEGA (CONTROLLINO_D0 FOR CONTROLLINO MAXI)

// ROTARY ENCODER WITH SWITCH
#define ROTARY_ENCODER_ST							3 					// DIN(EINT) #3 FOR ARDUINO MEGA (CONTROLLINO_D1 FOR CONTROLLINO MAXI)
#define ROTARY_ENCODER_DI							4					// DIN       #4 FOR ARDUINO MEGA (CONTROLLINO_D2 FOR CONTROLLINO MAXI)
#define ROTARY_ENCODER_SW							5					// DIN(POLL) #5 FOR ARDUINO MEGA (CONTROLLINO_D3 FOR CONTROLLINO MAXI)

// BREW BUTTON LED (NOT ATTACHED)
#define BREW_BUTTON_LED								6					// DOUT #6 FOR ARDUINO MEGA (CONTROLLINO_D4 FOR CONTROLLINO MAXI)

// LED PIXEL FOR VISUALIZATION
#define NEOPIXEL_DIN								7					// DOUT #7 FOR ARDUINO MEGA (CONTROLLINO_D5 FOR CONTROLLINO MAXI)

// PROPORTIONAL CONTROLLED SOLENOID VALVE
#define GROUPHEAD_LAMP								8					// DOUT(PWM) #8 FOR ARDUINO MEGA (CONTROLLINO_D6 FOR CONTROLLINO MAXI)

// PROPORTIONAL CONTROLLED SOLENOID VALVE (NOT ATTACHED)
#define PCTL_SOLENOID_VALVE							11					// DOUT(PWM) #11 FOR ARDUINO MEGA (CONTROLLINO_D9 FOR CONTROLLINO MAXI)

// AUX. GPIO INTERFACE (EINT, CH1)
#define AUX_GPIO_EINT								19					// DIN(EINT) #19 FOR ARDUINO MEGA (CONTROLLINO_IN1 FOR CONTROLLINO MAXI)
#define AUX_GPIO_CH1								13					// DOUT(PWM) #13 FOR ARDUINO MEGA (CONTROLLINO_D11 FOR CONTROLLINO MAXI)

// BLDC MOTOR CONTROLLER FOR PUMP
#define BLDC_MOTOR_SPEED							9					// DOUT(PWM) #9 FOR ARDUINO MEGA (CONTROLLINO_D7 FOR CONTROLLINO MAXI)
#define BLDC_MOTOR_STOP								22					// DOUT(RLY) #22 FOR ARDUINO MEGA (CONTROLLINO_R0 FOR CONTROLLINO MAXI)
#define BLDC_MOTOR_RESET							23					// DOUT(RLY) #23 FOR ARDUINO MEGA (CONTROLLINO_R1 FOR CONTROLLINO MAXI)
#define BLDC_MOTOR_ALARM							A10					// DIN       A10 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define BLDC_MOTOR_SPEEDOUT							A11					// DIN       A11 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)

// WATER FLOWMETER SENSOR
#define WATER_FLOWMETER								18					// DIN(EINT) #18 FOR ARDUINO MEGA (CONTROLLINO IN0 FOR CONTROLLINO MAXI)
#define AUX_EXTERNAL_INTERRUPT						AUX_GPIO_EINT		// DIN(EINT) #19 FOR ARDUINO MEGA (CONTROLLINO IN1 FOR CONTROLLINO MAXI)

// I2C BUS (TEXT LCD MODULE ON I2C BUS)
#define I2C_SDA										20					// DIO  #20 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define I2C_SCL										21					// DOUT #21 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)

// SOLENOID VALVE
#define BREW_SOLENOID_VALVE							28					// DOUT(RLY) #28 FOR ARDUINO MEGA (CONTROLLINO_R6 FOR CONTROLLINO MAXI)
// #define AUX_SOLENOID_VALVE						29					// DOUT(RLY) #29 FOR ARDUINO MEGA (CONTROLLINO_R7 FOR CONTROLLINO MAXI)

// OPTICAL FIBER AMP POWER (AUTO-FLUSHING SENSOR)
#define OPTICAL_FIBER_AMP_POWER						29					// DOUT(RLY) #29 FOR ARDUINO MEGA (CONTROLLINO_R7 FOR CONTROLLINO MAXI)
#define OPTICAL_FIBER_SIGNAL						A6					// DIN       A6 FOR ARDUINO MEGA (CONTROLLINO_A6 FOR CONTROLLINO MAXI)
#define OPTICAL_FIBER_DIAGNOSIS						A7					// DIN       A7 FOR ARDUINO MEGA (CONTROLLINO_A7 FOR CONTROLLINO MAXI)

// TEXT LCD MODULE (BACKLIGHT MODE - NOT ATTACHED)
#define LCD_BACKLIGHT_LSB							42					// DOUT #42 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define LCD_BACKLIGHT_MSB							43					// DOUT #43 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)

// SPI BUS (RTC AND ETHERNET CHIPSET ON SPI BUS)
// INTERFACE FOR AUX. DEVICE WITH SPI
#define SPI_MISO									50					// DOUT #50 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define SPI_MOSI									51					// DIN  #51 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define SPI_SCK										52					// DOUT #52 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define SPI_SS 										53					// DOUT #53 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)

// ANALOG PRESSURE SENSOR (4-20mA, OP-AMP - CURRENT)
#define BREW_PRESSURE_SENSOR						A0					// AIN(ADC0) A0 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)
#define FEED_PRESSURE_SENSOR						A1 					// AIN(ADC1) A1 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)

// AUX. ANALOG_INTERFACE (4-20mA, OP-AMP - CURRENT)
#define AUX_ANALOG_CH1								A2					// AIN(ADC2) A2 FOR ARDUINO MEGA (PIN HEADER FOR CONTROLLINO MAXI)

// AUX. ANALOG INTERFACE (0-24V - VOLTAGE)
#define AUX_ANALOG_CH2								A3 					// AIN(ADC3) A3 FOR ARDUINO MEGA (CONTROLLINO_A3 FOR CONTROLLINO MAXI)
#define AUX_ANALOG_CH3								A4 					// AIN(ADC4) A4 FOR ARDUINO MEGA (CONTROLLINO_A4 FOR CONTROLLINO MAXI)
#define AUX_ANALOG_CH4								A5 					// AIN(ADC5) A5 FOR ARDUINO MEGA (CONTROLLINO_A5 FOR CONTROLLINO MAXI)

// AUX. GPIO INTERFACE (CH2)
#define AUX_GPIO_CH2								A8					// AIN(ADC8) A8 FOR ARDUINO MEGA (CONTROLLINO_A8 FOR CONTROLLINO MAXI)
#define AUX_GPIO_CH3								A9					// AIN(ADC9) A9 FOR ARDUINO MEGA (CONTROLLINO_A9 FOR CONTROLLINO MAXI)


#endif//_MES_HARDWARE_MAP_H_

