#ifndef _MES_SETUPMENU_TEMPLATE_H_
#define _MES_SETUPMENU_TEMPLATE_H_


#include "MES_Config.h"


////////////////////////////////////////////////////////////
// 			TEXT LCD TEMPLATE

// 											|01234567890123456789|
#define HEADER_MACHINE_NAME_STRING			"MOAI EspressoStation"
#define HEADER_MACHINE_MODEL_STRING			HARDWARE_MODELNAME
#define HEADER_MACHINE_MAKER_STRING			"  [Vidastech Inc.]  "

#define HEADER_MACHINE_INIT_STRING			"Machine Initialize.."
#define HEADER_MACHINE_FACTORY_STRING		"Factory Default Set!"

#define HEADER_TM4_COMM_SETTING_PASS_STRING	" TM4 COMM. SET PASS "
#define HEADER_TM4_COMM_SETTING_FAIL_STRING	" TM4 COMM. SET FAIL "
#define HEADER_SYSTEM_REBOOT_STRING			"    REBOOT SYSTEM   "


// 											|01234567890123456789|
#define LCD_BLANK_CHAR						' '

#define LCD_ZERO_CHAR						'0'
#define LCD_ONE_CHAR						'1'
#define LCD_TWO_CHAR						'2'
#define LCD_THREE_CHAR						'3'
#define LCD_FOUR_CHAR						'4'
#define LCD_FIVE_CHAR						'5'
#define LCD_SIX_CHAR						'6'
#define LCD_SEVEN_CHAR						'7'
#define LCD_EIGHT_CHAR						'8'
#define LCD_NINE_CHAR						'9'
#define LCD_ASTERISK_CHAR					'*'
#define LCD_PLUS_CHAR						'+'
#define LCD_MINUS_CHAR						'-'

#define LCD_PROGRAM1_CHAR					LCD_ONE_CHAR
#define LCD_PROGRAM2_CHAR					LCD_TWO_CHAR
#define LCD_FLOW_STRING						"FLOW"
#define LCD_TIME_STRING						"TIME"
#define LCD_ON_STRING 						"ON "
#define LCD_OFF_STRING						"OFF"
#define LCD_YES_STRING						"YES"
#define LCD_NO_STRING 						"NO "
#define LCD_HIGH_STRING						"HIGH"
#define LCD_LOW_STRING						"LOW "
#define LCD_RUN_STRING						"RUN "
#define LCD_STOP_STRING						"STOP"
#if AUTOMATION_SENSOR_ATTACHED
#define LCD_STANDBY_MODE_OFF_STRING			"OFF "
#define LCD_STANDBY_MODE_PREP_STRING 		"PREP"
#define LCD_STANDBY_MODE_SHOT_STRING 		"SHOT"
#endif
#define LCD_LAMP_OFF_STRING 				"OFF   "
#define LCD_LAMP_SHOT_STRING				"SHOT  "
#define LCD_LAMP_ALWAYS_STRING				"ALWAYS"
#define LCD_LED_PROGRESS_STRING				"PROGRESS"
#define LCD_LED_TIMELAPSE_STRING			"SHOTTIME"
#define LCD_LED_FLOWRATE_STRING				"FLOWRATE"
#define LCD_LED_BREW_PRESS_STRING			"BREWPRES"
#define LCD_LED_PUMP_PRESS_STRING			"PUMPPRES"
#define LCD_SUN_STRING						"SUN"
#define LCD_MON_STRING						"MON"
#define LCD_TUE_STRING						"TUE"
#define LCD_WED_STRING 						"WED"
#define LCD_THU_STRING 						"THU"
#define LCD_FRI_STRING 						"FRI"
#define LCD_SAT_STRING 						"SAT"
#define LCD_PREHEAT_STRING					"PREHEAT"
#define LCD_BREW_STRING						"BREW B "
#define LCD_GROUPHEAD_STRING				"GRPHEAD"
#define LCD_BREWWATER_STRING				"BREW W "
#define LCD_MVHIGH_LIMIT_STRING				"MV HIGH"
#define LCD_INPUT_BIAS_STRING				"TSENSOR"
// #define LCD_INPUT_BIAS_STRING				"BIAS   "
#define LCD_BREWPRES_STRING					"BREWPRES"
#define LCD_FEEDPRES_STRING					"FEEDPRES"
#define LCD_AUXPRES_STRING 					"AUXPRESS"
#define LCD_NONE_STRING						"NONE"


// MESSAGE: SUCCESS / FAILURE
// 											|01234567890123456789|
// #define LCD_SAVE_SUCCESS_STRING				"[SUCCESSFULLY SAVED]"
// #define LCD_SAVE_FAILURE_STRING				"  [FAILED TO SAVE]  "

// MESSAGE : SYSTEM ERROR
// 											|01234567890123456789|
#define LCD_BLANK_LINE_STRING				"                    "
#define LCD_ERROR_HEADER_STRING				"       [ERROR]      "
#define LCD_SYSTEM_OVERLOAD_STRING			"  SYSTEM  OVERLOAD  "
#define LCD_LOW_BREW_PRESSURE_STRING		"STANDBY PRESSURE ERR"
#define LCD_BREW_PRESSURE_OVER_STRING		" BREW OVER PRESSURE "
#define LCD_BREW_PRESSURE_UNDER_STRING		" BREW UNDER PRESSURE"
#if PUMP_PRESSURE_SENSOR_ATTACHED
#define LCD_LOW_INLET_PRESSURE_STRING		" LOW INLET PRESSURE "
#else
#define LCD_LOW_INLET_PRESSURE_STRING		""
#endif
#define LCD_GROUPHEAD_OVERHEAT_STRING		" GROUPHEAD OVERHEAT "
#define LCD_BREWBOILER_OVERHEAT_STRING		"   BREW B OVERHEAT  "
#define LCD_PREHEATBOILER_OVERHEAT_STRING	" PREHEAT B OVERHEAT "
#define LCD_GROUPHEAD_UNDERHEAT_STRING		" GROUPHEAD LOW HEAT "
#define LCD_BREWBOILER_UNDERHEAT_STRING		"   BREW B LOW HEAT  "
#define LCD_PREHEATBOILER_UNDERHEAT_STRING	" PREHEAT B LOW HEAT "
#define LCD_TEMPERATURE_SENSOR_ERROR_STRING	"  TEMP SENSOR FAIL  "

// MESSAGE : SYSTEM NOTICE
// 											|01234567890123456789|
#define LCD_NOTICE_HEADER_STRING			"      [NOTICE]      "
#define LCD_FLOWMETER_FAILURE_STRING		"  FLOWMETER FAILED  "
#define LCD_MOTOR_ALARM_STRING				"MOTOR ALARM RECEIVED"
#define LCD_MAINTENANCE_REQUIRED_STRING		"MAINTENANCE REQUIRED"
#define LCD_FLOWRATE_EXCEEDED_STRING		"   FLOWRATE LIMIT   "
#if AUTOMATION_SENSOR_ATTACHED
#define LCD_OPTICAL_FIBER_UNSTABLE_STRING	"OPTICAL SENSOR CHECK"
#else
#define LCD_OPTICAL_FIBER_UNSTABLE_STRING	""
#endif
#ifdef _USE_EEPROM_WORN_OUT_NOTICE_MESSAGE_
#define LCD_EEPROM_WORN_STRING				"   EEPROM WORN OUT  "
#else
#define LCD_EEPROM_WORN_STRING				""
#endif

// MESSAGE : SENSOR SETUP NOTICE
// 											|01234567890123456789|
// #define LCD_NOTICE_HEADER_STRING 		"      [NOTICE]      "
#define LCD_SENSOR_ADJ_NOTICE_STRING		"ADJ. ZEROSHIFT FIRST"
#define LCD_SENSOR_ADJ_FAIL_STRING			" (SPAN ADJ. FAILED) "
#define LCD_SENSOR_ZEROSHIFT_ADJ_STRING		" ZERO SHIFT ADJUSTED"
#define LCD_SENSOR_SPAN_ADJ_STRING			"   SPAN  ADJUSTED   "
#define LCD_SENSOR_DEFAULT_ADJ_STRING		"SENSOR DEFAULT RESET"

// MESSAGE: DASHBOARD / SETUP MENU ENTRY
// 											|01234567890123456789|
#define LCD_DASHBOARD_ENTRY_STRING			"    [DASHBOARD]     "
#define LCD_SETUPMENU_ENTRY_STRING			"    [SETUP MENU]    "
#define LCD_CLEANING_MODE_ENTRY_STRING		"  [CLEANING  MODE]  "

// MESSAGE: SAVE / CANCEL
// 											|01234567890123456789|
#define LCD_SAVE_STRING						"       [SAVE]       "
#define LCD_CANCEL_STRING					"      [CANCEL]      "
#define LCD_EXIT_STRING						"       [EXIT]       "
#define LCD_RESET_STRING					"       [RESET]      "
#define LCD_CLEANING_READY_STRING			"  PUSH BREW BUTTON  "
#define LCD_CLEANING_MODE_STRING			"   [NOW CLEANING]   "
#define LCD_PW_VERIFY_STRING				"      [VERIFY]      "
#define LCD_PW_PASS_STRING					"        PASS        "
#define LCD_PW_FAIL_STRING					"        FAIL        "
#define LCD_PWS_CONTINUE_STRING				" CONTINUE POWER SAVE"
#define LCD_PWS_INACTIVE_STRING				"  POWER SAVING OFF  "

// DASHBOARD PAGE A
// 											|01234567890123456789|
#define LCD_DASHBOARD_LINE0_TEMPLATE_A		"SHOT TIME   :       "
#define LCD_DASHBOARD_LINE1_TEMPLATE_A		"BREW VOLUME :       "
#define LCD_DASHBOARD_LINE2_TEMPLATE_A		"BREW B TEMP :       "
#define LCD_DASHBOARD_LINE3_TEMPLATE_A		"BREW B PRES :       "

// DASHBOARD PAGE B
// 											|01234567890123456789|
#if BREW_WATER_TEMPERATURE_SENSOR_ATTACHED
#define LCD_DASHBOARD_LINE0_TEMPLATE_B		"GROUP  TEMP :       "
#define LCD_DASHBOARD_LINE1_TEMPLATE_B		"BREW B TEMP :       "
#define LCD_DASHBOARD_LINE2_TEMPLATE_B		"PRE  B TEMP :       "
#define LCD_DASHBOARD_LINE3_TEMPLATE_B		"BREW W TEMP :       "
#else
#define LCD_DASHBOARD_LINE0_TEMPLATE_B		"SHOT TIME   :       "
#define LCD_DASHBOARD_LINE1_TEMPLATE_B		"GROUP  TEMP :       "
#define LCD_DASHBOARD_LINE2_TEMPLATE_B		"BREW B TEMP :       "
#define LCD_DASHBOARD_LINE3_TEMPLATE_B		"PRE  B TEMP :       "
#endif

// DASHBOARD PAGE C
// 											|01234567890123456789|
#define LCD_DASHBOARD_LINE0_TEMPLATE_C		"SHOT TIME    :      "
#define LCD_DASHBOARD_LINE1_TEMPLATE_C		"CUR FLOWRATE :      "
#define LCD_DASHBOARD_LINE2_TEMPLATE_C		"AVG FLOWRATE :      "
#define LCD_DASHBOARD_LINE3_TEMPLATE_C		"AVG PRESSURE :      "

// SETUP TOP PAGE 1
// 											|01234567890123456789|
#define LCD_SETUPMENU_LINE0_TEMPLATE_1		" 1.PROGRAM 1 SETUP  "
#define LCD_SETUPMENU_LINE1_TEMPLATE_1		" 2.PROGRAM 2 SETUP  "
#define LCD_SETUPMENU_LINE2_TEMPLATE_1		" 3.MANUAL    SETUP  "
#define LCD_SETUPMENU_LINE3_TEMPLATE_1		" 4.INJECTION SETUP  "

// SETUP TOP PAGE 2
// 											|01234567890123456789|
#define LCD_SETUPMENU_LINE0_TEMPLATE_2		" 5.GROUP  TEMP SETUP"
#define LCD_SETUPMENU_LINE1_TEMPLATE_2		" 6.BREW B TEMP SETUP"
#define LCD_SETUPMENU_LINE2_TEMPLATE_2		" 7.PRE  B TEMP SETUP"
#define LCD_SETUPMENU_LINE3_TEMPLATE_2		" 8.MOTOR PUMP SETUP "

// SETUP TOP PAGE 3
// 											|01234567890123456789|
#define LCD_SETUPMENU_LINE0_TEMPLATE_3		" 9. LAMP SETUP      "
#define LCD_SETUPMENU_LINE1_TEMPLATE_3		" 10.LED MODE SETUP  "
#define LCD_SETUPMENU_LINE2_TEMPLATE_3		" 11.TIME DATE SETUP "
#define LCD_SETUPMENU_LINE3_TEMPLATE_3		" 12.POWER SAVING    "

// SETUP TOP PAGE 4
// 											|01234567890123456789|
#define LCD_SETUPMENU_LINE0_TEMPLATE_4		" 13.HEATER SETUP    "
#define LCD_SETUPMENU_LINE1_TEMPLATE_4		" 14.SENSOR SETUP    "
#define LCD_SETUPMENU_LINE2_TEMPLATE_4		" 15.MOTOR ACC SETUP "
#if AUTOMATION_SENSOR_ATTACHED
#define LCD_SETUPMENU_LINE3_TEMPLATE_4		" 16.AUTOMATION SETUP"
#else
#define LCD_SETUPMENU_LINE3_TEMPLATE_4		" 16.FLUSHING DETECT "
#endif

// SETUP TOP PAGE 5
// 											|01234567890123456789|
#define LCD_SETUPMENU_LINE0_TEMPLATE_5		" 17.MAINTENANCE     "
#define LCD_SETUPMENU_LINE1_TEMPLATE_5		" 18.RESET           "
#define LCD_SETUPMENU_LINE2_TEMPLATE_5		" 19.INFORMATION     "
#define LCD_SETUPMENU_LINE3_TEMPLATE_5		" 20.AUTHORIZATION   "

// 1. PROGRAM 1 SETUP
// 2. PROGRAM 2 SETUP
// 											|01234567890123456789|
#define LCD_PROGRAM_LINE0_TEMPLATE  		"PROGRAM MODE:       "
#define LCD_PROGRAM_LINE1_TEMPLATE 			"INJECTION   :       "
#define LCD_PROGRAM_LINE2_TEMPLATE 			"EXTRACTION  :       "
#define LCD_PROGRAM_LINE3_TEMPLATE 			"TOTAL       :       "

// 3. MANUAL SETUP
// 											|01234567890123456789|
#define LCD_MANUAL_LINE0_TEMPLATE 			"MANUAL MODE         "
#define LCD_MANUAL_LINE1_TEMPLATE 			"SAVE TO PROG#:      "
#define LCD_MANUAL_LINE2_TEMPLATE 			"SHOT TIME   :       "
#define LCD_MANUAL_LINE3_TEMPLATE 			"BREW VOLUME :       "

// 4. INJECTION SETUP
// 											|01234567890123456789|
#define LCD_INJECTION_LINE0_TEMPLATE		"INJECTION MODE      "
#define LCD_INJECTION_LINE1_TEMPLATE		"ACTIVATION     :    "
#define LCD_INJECTION_LINE2_TEMPLATE		"INJECTION POWER:    "
#define LCD_INJECTION_LINE3_TEMPLATE		"                    "

// 5. GROUP TEMP SETUP
// 											|01234567890123456789|
#define LCD_GROUPTEMP_LINE0_TEMPLATE		"GROUPHEAD TEMP SETUP"
#define LCD_GROUPTEMP_LINE1_TEMPLATE		"PRESENT TEMP :      "
#define LCD_GROUPTEMP_LINE2_TEMPLATE		"SET     TEMP :      "
#define LCD_GROUPTEMP_LINE3_TEMPLATE		"HEATING MV   :      "

// 6. BREW B TEMP SETUP
// 											|01234567890123456789|
#define LCD_BREWTEMP_LINE0_TEMPLATE			"BREW B TEMP SETUP   "
#define LCD_BREWTEMP_LINE1_TEMPLATE			"PRESENT TEMP :      "
#define LCD_BREWTEMP_LINE2_TEMPLATE			"SET     TEMP :      "
#define LCD_BREWTEMP_LINE3_TEMPLATE		 	"HEATING MV   :      "

// 7. PRE B TEMP SETUP
// 											|01234567890123456789|
#define LCD_PRETEMP_LINE0_TEMPLATE			"PREHEAT B TEMP SETUP"
#define LCD_PRETEMP_LINE1_TEMPLATE			"PRESENT TEMP :      "
#define LCD_PRETEMP_LINE2_TEMPLATE			"SET     TEMP :      "
#define LCD_PRETEMP_LINE3_TEMPLATE		 	"HEATING MV   :      "

// 8. PUMP SETUP
// 											|01234567890123456789|
#define LCD_MOTORPUMP_LINE0_TEMPLATE		"MOTOR POWER  :      "
#define LCD_MOTORPUMP_LINE1_TEMPLATE		"STANDBY MODE :      "
#define LCD_MOTORPUMP_LINE2_TEMPLATE		"MOTOR RUN    :      "
#define LCD_MOTORPUMP_LINE3_TEMPLATE		"BREW B PRES  :      "

// 9. LAMP SETUP
// 											|01234567890123456789|
#define LCD_LAMP_LINE0_TEMPLATE				"LAMP SETUP          "
#define LCD_LAMP_LINE1_TEMPLATE				"LAMP MODE  :        "
#define LCD_LAMP_LINE2_TEMPLATE				"BRIGHTNESS :        "
#define LCD_LAMP_LINE3_TEMPLATE				"                    "

// 10. LED PIXEL SETUP
// 											|01234567890123456789|
#define LCD_LEDPIXEL_LINE0_TEMPLATE			"LED MODE SETUP      "
#define LCD_LEDPIXEL_LINE1_TEMPLATE			"PROGRAM 1 :         "
#define LCD_LEDPIXEL_LINE2_TEMPLATE			"PROGRAM 2 :         "
#define LCD_LEDPIXEL_LINE3_TEMPLATE			"MANUAL    :         "

// 11. TIME DATE SETUP
// 											|01234567890123456789|
#define LCD_TIMEDATE_LINE0_TEMPLATE			"TIME DATE SETUP     "
#define LCD_TIMEDATE_LINE1_TEMPLATE			"DATE     /    /     "
#define LCD_TIMEDATE_LINE2_TEMPLATE			"TIME     :    :     "
#define LCD_TIMEDATE_LINE3_TEMPLATE			"WDAY                "

// 12. POWER SAVING
// 											|01234567890123456789|
#define LCD_POWSAVE_LINE0_TEMPLATE			"POWER SAVING MODE   "
#define LCD_POWSAVE_LINE1_TEMPLATE			"ACTIVATION:         "
#define LCD_POWSAVE_LINE2_TEMPLATE			"START     :    : 00 "
#define LCD_POWSAVE_LINE3_TEMPLATE			"END       :    : 00 "

// 13. HEATER SETUP
// 											|01234567890123456789|
#define LCD_HEATER_PID_LINE0_TEMPLATE		"HEATER SET :        "
#define LCD_HEATER_PID_LINE1_TEMPLATE		"P-TEMP     :        "
#define LCD_HEATER_PID_LINE2_TEMPLATE		"I-TIME     :        "
#define LCD_HEATER_PID_LINE3_TEMPLATE		"D-TIME     :        "

// #define LCD_HEATER_MV_LINE0_TEMPLATE		"HEATER SET :        "
#define LCD_HEATER_MV_LINE1_TEMPLATE		"PREHEAT B  :        "
#define LCD_HEATER_MV_LINE2_TEMPLATE		"BREW B     :        "
#define LCD_HEATER_MV_LINE3_TEMPLATE		"GROUPHEAD  :        "

// #define LCD_HEATER_BIAS_LINE0_TEMPLATE	"HEATER SET :        "
#define LCD_HEATER_BIAS_LINE1_TEMPLATE		"CHANNEL    :        "
#define LCD_HEATER_BIAS_LINE2_TEMPLATE		"INPUT BIAS :        "
#define LCD_HEATER_BIAS_LINE3_TEMPLATE		"                    "

// 14. PRESSURE SENSOR ADJUSTMENT
// 											|01234567890123456789|
#define LCD_SENSOR_ADJ_LINE0_TEMPLATE		"          ADC:      "
#define LCD_SENSOR_ADJ_LINE1_TEMPLATE		" ZERO SHIFT (0 BAR) "
#define LCD_SENSOR_ADJ_LINE2_TEMPLATE		" SPAN      (10 BAR) "
#define LCD_SENSOR_ADJ_LINE3_TEMPLATE		" DEFAULT RESET      "

// 15. MOTOR ACC SETUP
// 											|01234567890123456789|
#define LCD_MOTOR_ACC_LINE0_TEMPLATE		"MOTOR ACC SETUP     "
#define LCD_MOTOR_ACC_LINE1_TEMPLATE		"ACC TIME (MS):      "
#define LCD_MOTOR_ACC_LINE2_TEMPLATE		"MOTOR POWER  :      "
#define LCD_MOTOR_ACC_LINE3_TEMPLATE		"EST TIME (MS):      "

// 16. FLUSHING DETECTION (<v1.4.0) / AUTOMATION SETUP (>v2.0.0)
// 											|01234567890123456789|
#if AUTOMATION_SENSOR_ATTACHED
#define LCD_AUTOMATION_LINE0_TEMPLATE		"AUTOMATION SETUP    "
#define LCD_AUTOMATION_LINE1_TEMPLATE		"ACTIVATION:         "
#define LCD_AUTOMATION_LINE2_TEMPLATE		"FLUSH TIME:         "
#define LCD_AUTOMATION_LINE3_TEMPLATE		"BREW START:         "
#else
#define LCD_FLUSHING_LINE0_TEMPLATE			"FLUSHING DETECTION  "
#define LCD_FLUSHING_LINE1_TEMPLATE			"ACTIVATION:         "
#define LCD_FLUSHING_LINE2_TEMPLATE			"TIME      :         "
#define LCD_FLUSHING_LINE3_TEMPLATE			"PRESSURE  :         "
#endif

// 17. MAINTENANCE
// 											|01234567890123456789|
#define LCD_MAINTENANCE_LINE0_TEMPLATE		"MAINTENANCE:        "
#define LCD_MAINTENANCE_LINE1_TEMPLATE		"TOTAL FLOW :        "
#define LCD_MAINTENANCE_LINE2_TEMPLATE		"TOTAL BREW :        "
#define LCD_MAINTENANCE_LINE3_TEMPLATE		"ERROR CODE :        "

// 18. RESET
// 											|01234567890123456789|
#define LCD_RESET_LINE0_TEMPLATE			"RESET MACHINE       "
#define LCD_RESET_LINE1_TEMPLATE			"                    "
#define LCD_RESET_LINE2_TEMPLATE			"                    "
#define LCD_RESET_LINE3_TEMPLATE			"                    "

// 19. INFORMATION
// 											|01234567890123456789|
#define LCD_SYSTEM_INFO_LINE0_TEMPLATE		"   VIDASTECH INC.   "
#define LCD_SYSTEM_INFO_LINE1_TEMPLATE		"MODEL NO:           "
#define LCD_SYSTEM_INFO_LINE2_TEMPLATE		"H/W VER :           "
#define LCD_SYSTEM_INFO_LINE3_TEMPLATE		"S/W VER :           "

// 20. PASSWORD
// 											|01234567890123456789|
#define LCD_PASSWORD_LINE0_TEMPLATE			"      PASSWORD      "
#define LCD_PASSWORD_LINE1_TEMPLATE			"                    "
#define LCD_PASSWORD_LINE2_TEMPLATE			"                    "
#define LCD_PASSWORD_LINE3_TEMPLATE			"                    "


// TEXT LCD POSITION

#define HOME_CURSOR_POS						(0)
#define HOME_CURSOR_LINE					(0)

// ERROR MESSAGE
#define ERROR_HEADER_LINE					(0)
#define ERROR_MESSAGE_LINE					(1)
#define ERROR_CODE_LINE 					(2)
#define ERROR_CODE_POS						(8)

// NOTICE MESSAGE
#define NOTICE_HEADER_LINE					(0)
#define NOTICE_MESSAGE_LINE 				(1)
#define NOTICE_CODE_LINE					(2)
#define NOTICE_CODE_POS						(8)

// ENTRY MESSAGE
#define ENTRY_MESSAGE_LINE					(1)

// SAVE MESSAGE
#define SAVE_MESSAGE_LINE					(1)

// CANCEL MESSAGE
#define CANCEL_MESSAGE_LINE					(1)

// CLEANING MODE MESSAGE
#define CLEANING_HEADER_LINE				(1)
#define CLEANING_MESSAGE_LINE				(2)

// DASHBOARD PAGE A
#define DASHBOARD_A_SUBTITLE_DIGIT			(13)
#define DASHBOARD_A_SUBVALUE_POS			(DASHBOARD_A_SUBTITLE_DIGIT + 1)

#define SHOT_TIME_VALUE_LINE				(0)
#define FLOW_QTY_A_VALUE_LINE				(1)
#define BREW_TEMP_VALUE_LINE				(2)
#define PRESSURE_VALUE_LINE					(3)

// DASHBOARD PAGE B
#define DASHBOARD_B_SUBTITLE_DIGIT			(13)
#define DASHBOARD_B_SUBVALUE_POS			(DASHBOARD_B_SUBTITLE_DIGIT + 1)

#if BREW_WATER_TEMPERATURE_SENSOR_ATTACHED
#define GROUP_TEMP_VALUE_LINE				(0)
#define BREW_B_TEMP_VALUE_LINE				(1)
#define PRE_B_TEMP_VALUE_LINE				(2)
#define BREW_WATER_TEMP_VALUE_LINE			(3)
#else
//#define SHOT_TIME_VALUE_LINE				(0)
#define GROUP_TEMP_VALUE_LINE				(1)
#define BREW_B_TEMP_VALUE_LINE				(2)
#define PRE_B_TEMP_VALUE_LINE				(3)
#endif

// DASHBOARD PAGE C
#define DASHBOARD_C_SUBTITLE_DIGIT			(14)
#define DASHBOARD_C_INDICATOR_POS			(DASHBOARD_C_SUBTITLE_DIGIT)
#define DASHBOARD_C_SUBVALUE_POS			(DASHBOARD_C_SUBTITLE_DIGIT + 1)

//#define SHOT_TIME_VALUE_LINE				(0)
#define FLOW_RATE_C_VALUE_LINE				(1)
#define AVG_FLOW_RATE_VALUE_LINE			(2)
#define AVG_PRESSURE_VALUE_LINE				(3)

// SETUP TOP PAGE 1
#define LCD_SETUPMENU_PROGRAM1_LINE			(0)
#define LCD_SETUPMENU_PROGRAM2_LINE 		(1)
#define LCD_SETUPMENU_MANUAL_LINE			(2)
#define LCD_SETUPMENU_INJECTION_LINE 		(3)

// SETUP TOP PAGE 2
#define LCD_SETUPMENU_GROUPHEAD_B_LINE 		(0)
#define LCD_SETUPMENU_BREW_B_LINE 			(1)
#define LCD_SETUPMENU_PREHEAT_B_LINE 		(2)
#define LCD_SETUPMENU_MOTORPUMP_LINE 		(3)

// SETUP TOP PAGE 3
#define LCD_SETUPMENU_LAMP_LINE 			(0)
#define LCD_SETUPMENU_LEDPIXEL_LINE 		(1)
#define LCD_SETUPMENU_TIMEDATE_LINE 		(2)
#define LCD_SETUPMENU_POWERSAVE_LINE 		(3)

// SETUP TOP PAGE 4
#define LCD_SETUPMENU_HEATER_LINE			(0)
#define LCD_SETUPMENU_SENSOR_LINE 			(1)
#define LCD_SETUPMENU_MOTOR_ACC_LINE		(2)
#define LCD_SETUPMENU_CLEANING_LINE			(3)

// SETUP TOP PAGE 5
#define LCD_SETUPMENU_MAINTENANCE_LINE 		(0)
#define LCD_SETUPMENU_RESET_LINE 			(1)
#define LCD_SETUPMENU_INFORMATION_LINE		(2)
#define LCD_SETUPMENU_PASSWORD_LINE			(3)

// 1. 2. PROGRAM 1/2 SETUP
#define PROGRAM_SETUP_SUBTITLE_DIGIT		(13)
#define PROGRAM_SETUP_SUBVALUE_POS			(PROGRAM_SETUP_SUBTITLE_DIGIT + 1)

#define PROGRAM_MODE_VALUE_LINE				(0)
#define INJECTION_VALUE_LINE				(1)
#define EXTRACTION_VALUE_LINE				(2)
#define TOTAL_TIME_VALUE_LINE				(3)

// 3. MANUAL SETUP
#define MANUAL_SETUP_SUBTITLE_DIGIT			(14)
#define MANUAL_SETUP_SUBVALUE_POS			(MANUAL_SETUP_SUBTITLE_DIGIT + 1)
#define MANUAL_SHOT_SUBVALUE_POS			(MANUAL_SETUP_SUBTITLE_DIGIT)

#define SAVE_TO_PROG_NUM_VALUE_LINE			(1)
#define MANUAL_SHOT_TIME_VALUE_LINE			(2)
#define MANUAL_FLOW_QUANTITY_VALUE_LINE		(3)

// 4. INJECTION SETUP
#define INJECTION_SETUP_SUBTITLE_DIGIT		(16)
#define INJECTION_SETUP_SUBVALUE_POS		(INJECTION_SETUP_SUBTITLE_DIGIT + 1)

#define INJECTION_MODE_VALUE_LINE			(1)
#define INJECTION_POWER_VALUE_LINE			(2)

// 5. 6. 7. GROUP/BREW B/PRE B TEMP SETUP
#define BOILER_SETUP_SUBTITLE_DIGIT			(14)
#define BOILER_SETUP_SUBVALUE_POS			(BOILER_SETUP_SUBTITLE_DIGIT + 1)

#define PRESENT_TEMP_VALUE_LINE				(1)
#define SET_TEMP_VALUE_LINE					(2)
#define PRESENT_HEATING_MV_LINE				(3)

// 8. PUMP SETUP
#define PUMP_SETUP_SUBTITLE_DIGIT			(14)
#define PUMP_SETUP_SUBVALUE_POS				(PUMP_SETUP_SUBTITLE_DIGIT + 1)

#define MOTOR_POWER_VALUE_LINE				(0)
#define STANDBY_MODE_VALUE_LINE				(1)
#define MOTOR_RUN_VALUE_LINE				(2)
#define PUMP_PRESSURE_VALUE_LINE			(3)

// 9. LAMP SETUP
#define LAMP_SETUP_SUBTITLE_DIGIT			(12)
#define LAMP_SETUP_SUBVALUE_POS				(LAMP_SETUP_SUBTITLE_DIGIT + 1)

#define LAMP_MODE_VALUE_LINE				(1)
#define BRIGHTNESS_VALUE_LINE				(2)

// 10. LED PIXEL SETUP
#define LEDPIXEL_SETUP_SUBTITLE_DIGIT		(11)
#define LEDPIXEL_SETUP_SUBVALUE_POS			(LEDPIXEL_SETUP_SUBTITLE_DIGIT + 1)

#define PROGRAM1_INDICATOR_VALUE_LINE		(1)
#define PROGRAM2_INDICATOR_VALUE_LINE		(2)
#define MANUAL1_INDICATOR_VALUE_LINE		(3)

// 11. TIME DATE SETUP
#define TIMEDATE_SETUP_SUBTITLE_DIGIT		(5)
#define TIMEDATE_SETUP_SUBVALUE_POS			(TIMEDATE_SETUP_SUBTITLE_DIGIT + 1)
#define TIMEDATE_SETUP_YEAR_POS				(TIMEDATE_SETUP_SUBVALUE_POS)
#define TIMEDATE_SETUP_MONTH_POS 			(TIMEDATE_SETUP_YEAR_POS + 5)
#define TIMEDATE_SETUP_DAY_POS				(TIMEDATE_SETUP_MONTH_POS + 5)
#define TIMEDATE_SETUP_HOUR_POS				(TIMEDATE_SETUP_SUBVALUE_POS)
#define TIMEDATE_SETUP_MINUTE_POS			(TIMEDATE_SETUP_HOUR_POS + 5)
#define TIMEDATE_SETUP_SECOND_POS			(TIMEDATE_SETUP_MINUTE_POS + 5)
#define TIMEDATE_SETUP_WEEKDAY_POS			(TIMEDATE_SETUP_SUBVALUE_POS)

#define DATE_VALUE_LINE 					(1)
#define TIME_VALUE_LINE 					(2)
#define WDAY_VALUE_LINE						(3)

#define DATE_YEAR_SELECTION_POS				(TIMEDATE_SETUP_SUBTITLE_DIGIT)
#define DATE_MONTH_SELECTION_POS			(DATE_YEAR_SELECTION_POS + 5)
#define DATE_DAY_SELECTION_POS				(DATE_MONTH_SELECTION_POS + 5)
#define TIME_HOUR_SELECTION_POS				(TIMEDATE_SETUP_SUBTITLE_DIGIT)
#define TIME_MINUTE_SELECTION_POS			(TIME_HOUR_SELECTION_POS + 5)
#define TIME_SECOND_SELECTION_POS			(TIME_MINUTE_SELECTION_POS + 5)
#define WEEKDAY_SELECTION_POS				(TIMEDATE_SETUP_SUBTITLE_DIGIT)

// 12. POWER SAVING
#define POWER_SAVING_MODE_SUBTITLE_DIGIT	(11)
#define POWER_SAVING_TIME_SUBTITLE_DIGIT	(6)
#define POWER_SAVING_MODE_SUBVALUE_POS		(POWER_SAVING_MODE_SUBTITLE_DIGIT + 1)
#define POWER_SAVING_TIME_SUBVALUE_POS		(POWER_SAVING_TIME_SUBTITLE_DIGIT + 1)
#define POWER_SAVING_TIME_SETUP_HOUR_POS	(POWER_SAVING_TIME_SUBVALUE_POS)
#define POWER_SAVING_TIME_SETUP_MINUTE_POS	(POWER_SAVING_TIME_SETUP_HOUR_POS + 5)
#define POWER_SAVING_TIME_SETUP_SECOND_POS	(POWER_SAVING_TIME_SETUP_MINUTE_POS + 5)

#define POWER_SAVING_MODE_VALUE_LINE		(1)
#define BEGIN_TIME_VALUE_LINE				(2)
#define END_TIME_VALUE_LINE 				(3)
#define ACTIVATION_SELECTION_POS			(POWER_SAVING_MODE_SUBTITLE_DIGIT)
#define HOUR_SELECTION_POS					(POWER_SAVING_TIME_SUBTITLE_DIGIT)
#define MINUTE_SELECTION_POS				(HOUR_SELECTION_POS + 5)
#define SECOND_SELECTION_POS				(MINUTE_SELECTION_POS + 5)

// 13. HEATER SETUP
#define HEATER_SUBTITLE_DIGIT				(12)
#define HEATER_SUBVALUE_POS					(HEATER_SUBTITLE_DIGIT + 1)

#define HEATER_SET_VALUE_LINE				(0)
#define P_BAND_VALUE_LINE					(1)
#define I_TIME_VALUE_LINE					(2)
#define D_TIME_VALUE_LINE					(3)
#define PREHEAT_MV_VALUE_LINE				(P_BAND_VALUE_LINE)
#define BREW_MV_VALUE_LINE					(I_TIME_VALUE_LINE)
#define GROUPHEAD_MV_VALUE_LINE				(D_TIME_VALUE_LINE)
#define INPUT_SENSOR_CH_LINE				(P_BAND_VALUE_LINE)
#define INPUT_BIAS_VALUE_LINE				(I_TIME_VALUE_LINE)

// 14. SENSOR SETUP
#define SENSOR_SUBTITLE_DIGIT				(0)
#define SENSOR_CHANNEL_SUBVALUE_POS			(SENSOR_SUBTITLE_DIGIT + 1)
#define SENSOR_ADC_SUBVALUE_POS				(SENSOR_SUBTITLE_DIGIT + 15)

#define SENSOR_CHANNEL_VALUE_LINE			(0)
#define SENSOR_ZEROSHIFT_VALUE_LINE			(1)
#define SENSOR_SPAN_VALUE_LINE				(2)
#define SENSOR_DEFAULT_VALUE_LINE			(3)

// 15. MOTOR ACC SETUP
#define MOTOR_ACC_SUBTITLE_DIGIT			(14)
#define MOTOR_ACC_SUBVALUE_POS				(MOTOR_ACC_SUBTITLE_DIGIT + 1)

#define MOTOR_ACC_TIME_VALUE_LINE 			(1)
#define MOTOR_POWER_CUR_VALUE_LINE			(2)
#define MOTOR_ACC_TIME_EST_VALUE_LINE		(3)

// 16. FLUSHING DETECTION (<v1.4.0) / AUTOMATION SETUP (>v2.0.0)
#if AUTOMATION_SENSOR_ATTACHED
#define AUTOMATION_MODE_SUBTITLE_DIGIT		(11)
#define AUTOMATION_MODE_SUBVALUE_POS		(AUTOMATION_MODE_SUBTITLE_DIGIT + 1)

#define AUTOMATION_MODE_VALUE_LINE			(1)
#define AUTO_FLUSHING_TIME_VALUE_LINE		(2)
#define AUTO_BREW_WAIT_TIME_VALUE_LINE		(3)
#else
#define FLUSHING_DETECTION_SUBTITLE_DIGIT	(11)
#define FLUSHING_DETECTION_SUBVALUE_POS		(FLUSHING_DETECTION_SUBTITLE_DIGIT + 1)

#define FLUSHING_DETECTION_MODE_VALUE_LINE	(1)
#define FLUSHING_DETECTION_TIME_VALUE_LINE	(2)
#define FLUSHING_DETECTION_PRES_VALUE_LINE	(3)
#endif

// 17. MAINTENANCE
#define MAINTENANCE_SUBTITLE_DIGIT			(12)
#define MAINTENANCE_SUBVALUE_POS			(MAINTENANCE_SUBTITLE_DIGIT + 1)

#define MAINTENANCE_MODE_VALUE_LINE			(0)
#define TOTAL_FLOW_VALUE_LINE				(1)
#define TOTAL_BREW_VALUE_LINE				(2)
#define ERROR_CODE_VALUE_LINE				(3)

// 18. RESET
#define RESET_SUBTITLE_DIGIT				(8)
#define RESET_SUBVALUE_POS					(RESET_SUBTITLE_DIGIT + 1)

#define DEFAUT_SET_VALUE_LINE				(2)

// 19. INFORMATION
#define INFORMATION_SUBTITLE_DIGIT			(9)
#define IFNORMATION_SUBVALUE_POS			(INFORMATION_SUBTITLE_DIGIT + 1)

#define HARDWARE_MODEL_NAME_VALUE_LINE		(1)
#define HARDWARE_VERSION_VALUE_LINE			(2)
#define SOFTWARE_VERSION_VALUE_LINE			(3)

// 20. PASSWORD
#define PASSWORD_SUBTITLE_DIGIT				(4)
#define PASSWORD_SUBVALUE_POS				(PASSWORD_SUBTITLE_DIGIT + 1)
#define PASSWORD0_SUBVALUE_POS				(PASSWORD_SUBVALUE_POS)
#define PASSWORD1_SUBVALUE_POS				(PASSWORD0_SUBVALUE_POS + 3)
#define PASSWORD2_SUBVALUE_POS				(PASSWORD1_SUBVALUE_POS + 3)
#define PASSWORD3_SUBVALUE_POS				(PASSWORD2_SUBVALUE_POS + 3)

#define PASSWORD_VALUE_LINE					(2)
#define PASSWORD0_SELECTION_POS				(PASSWORD_SUBTITLE_DIGIT)
#define PASSWORD1_SELECTION_POS				(PASSWORD0_SELECTION_POS + 3)
#define PASSWORD2_SELECTION_POS				(PASSWORD1_SELECTION_POS + 3)
#define PASSWORD3_SELECTION_POS				(PASSWORD2_SELECTION_POS + 3)


#endif//_MES_SETUPMENU_TEMPLATE_H_

